//
// Created by vasilis on 22/05/20.
//

#ifndef CP_BUFFER_SIZES_H
#define CP_BUFFER_SIZES_H



#define PROP_BUF_SLOTS MAX((REM_MACH_NUM * PROP_CREDITS), (MAX_RECV_PROP_WRS + 1))
#define PROP_REP_BUF_SLOTS (REM_MACH_NUM * PROP_CREDITS)
#define ACC_REP_BUF_SLOTS (REM_MACH_NUM * ACC_CREDITS)
#define RMW_REP_BUF_SLOTS (PROP_REP_BUF_SLOTS + ACC_REP_BUF_SLOTS)
#define ACC_BUF_SLOTS MAX((REM_MACH_NUM * ACC_CREDITS), (MAX_RECV_ACC_WRS + 1))
#define COM_BUF_SLOTS ((REM_MACH_NUM * COM_CREDITS), (MAX_RECV_COM_WRS + 1))
#define ACK_BUF_SLOTS (REM_MACH_NUM * COM_CREDITS)





#endif //CP_BUFFER_SIZES_H
